name: 'Publish IntelliJ Plugin Verifier Report'
description: 'Publish IntelliJ Plugin Verifier report as a pull request comment.'

inputs:
  plugin-id:
    description: 'IntelliJ plugin ID'
    required: true
  plugin-version:
    description: 'IntelliJ plugin version'
    required: true
  plugin-verifier-report-path:
    description: 'Path to IntelliJ Plugin Verifier output report'
    required: true
    default: "${{ github.workspace }}/build/reports/pluginVerifier"
  repo-token:
    description: 'Repository token'
    required: true
    default: "${{ github.token }}"
runs:
  using: "composite"
  steps:
    - name: Consolidate Plugin Verifier Report
      shell: bash
      run: |
        ./verifier-report ${{ inputs.plugin-verifier-report-path }} ${{ inputs.plugin-id }} ${{ inputs.plugin-version }}
    - name: Publish Plugin Verifier Report
      uses: mshick/add-pr-comment@v2
      with:
        message-path: "${{ github.plugin-verifier-report-path }}.md"
        repo-token: "${{ inputs.repo-token }}"
